export const products = [
  {
    title: "Yellow Sweater",
    image: "/images/mock/product-example-1.png",
    stock: 6,
    tag: "Gomas deportivas",
    originalPrice: 77,
    currentPrice: 67,
  },
  {
    title: "Yellow Sweater",
    image: "/images/mock/product-example-1.png",
    stock: 6,
    tag: "Gomas deportivas",
    originalPrice: 77,
    currentPrice: 67,
  },
  {
    title: "Yellow Sweater",
    image: "/images/mock/product-example-1.png",
    stock: 6,
    tag: "Gomas deportivas",
    originalPrice: 77,
    currentPrice: 67,
  },
  {
    title: "Yellow Sweater",
    image: "/images/mock/product-example-1.png",
    stock: 6,
    tag: "Gomas deportivas",
    originalPrice: 77,
    currentPrice: 67,
  },
  {
    title: "Yellow Sweater",
    image: "/images/mock/product-example-1.png",
    stock: 6,
    tag: "Gomas deportivas",
    originalPrice: 77,
    currentPrice: 67,
  },
  {
    title: "Yellow Sweater",
    image: "/images/mock/product-example-1.png",
    stock: 6,
    tag: "Gomas deportivas",
    originalPrice: 77,
    currentPrice: 67,
  },
  {
    title: "Yellow Sweater",
    image: "/images/mock/product-example-1.png",
    stock: 6,
    tag: "Gomas deportivas",
    originalPrice: 77,
    currentPrice: 67,
  },
  {
    title: "Yellow Sweater",
    image: "/images/mock/product-example-1.png",
    stock: 6,
    tag: "Gomas deportivas",
    originalPrice: 77,
    currentPrice: 67,
  },
];
